### ISSUE TITLE
SK 제공자 404 에러가 발생합니다.

### ISSUE THREAD

**Issue by Taemni** [epg2xml/epg2xml#22]
로그를 확인해보니 2022-11-10 01:04:00.962 때부터 404 발생하기 시작했습니다.

2022-11-10 10:57:50.981 xmltv: /usr/bin/tv_grab_file: grab /usr/bin/tv_grab_file
2022-11-10 10:57:50.984 spawn: Executing "/usr/bin/tv_grab_file"
2022-11-10 10:57:51.497 spawn: 2022/11/10 10:57:51 INFO     PROV     121: [SK   ] 265 service channels loaded from cache.
2022-11-10 10:57:51.498 spawn: 2022/11/10 10:57:51 INFO     PROV     160: [SK   ] 요청 13 - 불가 0 = 최종 13
2022-11-10 10:57:51.498 spawn: 2022/11/10 10:57:51 INFO     MAIN      89: Writing xmltv.dtd header ...
2022-11-10 10:57:51.498 spawn: 2022/11/10 10:57:51 INFO     SK        72: 001/013 SBS <14.sk>
2022-11-10 10:57:51.603 spawn: 2022/11/10 10:57:51 ERROR    UTILS     40: 요청 중 에러:
2022-11-10 10:57:51.603 spawn: Traceback (most recent call last):
2022-11-10 10:57:51.603 spawn:   File "/usr/local/lib/python3.8/dist-packages/epg2xml/utils.py", line 34, in request_data
2022-11-10 10:57:51.603 spawn:     r.raise_for_status()
2022-11-10 10:57:51.603 spawn:   File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 960, in raise_for_status
2022-11-10 10:57:51.603 spawn:     raise HTTPError(http_error_msg, response=self)
2022-11-10 10:57:51.603 spawn: requests.exceptions.HTTPError: 404 Client Error: 404 for url: https://www.skbroadband.com/m/content/realtime/Channel_List.do?key_depth2=14&key_depth3=20221110
2022-11-10 10:57:52.643 spawn: 2022/11/10 10:57:52 ERROR    UTILS     40: 요청 중 에러:
2022-11-10 10:57:52.643 spawn: Traceback (most recent call last):
2022-11-10 10:57:52.643 spawn:   File "/usr/local/lib/python3.8/dist-packages/epg2xml/utils.py", line 34, in request_data
2022-11-10 10:57:52.643 spawn:     r.raise_for_status()
2022-11-10 10:57:52.643 spawn:   File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 960, in raise_for_status
2022-11-10 10:57:52.643 spawn:     raise HTTPError(http_error_msg, response=self)
2022-11-10 10:57:52.643 spawn: requests.exceptions.HTTPError: 404 Client Error: 404 for url: https://www.skbroadband.com/m/content/realtime/Channel_List.do?key_depth2=14&key_depth3=20221111
2022-11-10 10:57:53.684 spawn: 2022/11/10 10:57:53 ERROR    UTILS     40: 요청 중 에러:
2022-11-10 10:57:53.684 spawn: Traceback (most recent call last):
2022-11-10 10:57:53.684 spawn:   File "/usr/local/lib/python3.8/dist-packages/epg2xml/utils.py", line 34, in request_data
2022-11-10 10:57:53.684 spawn:     r.raise_for_status()
2022-11-10 10:57:53.684 spawn:   File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 960, in raise_for_status
2022-11-10 10:57:53.684 spawn:     raise HTTPError(http_error_msg, response=self)
2022-11-10 10:57:53.684 spawn: requests.exceptions.HTTPError: 404 Client Error: 404 for url: https://www.skbroadband.com/m/content/realtime/Channel_List.do?key_depth2=14&key_depth3=20221112
2022-11-10 10:58:45.696 spawn: 2022/11/10 10:58:45 INFO     MAIN     110: Done.
2022-11-10 10:58:45.726 xmltv: /usr/bin/tv_grab_file: grab took 55 seconds
2022-11-10 10:58:45.726 xmltv: /usr/bin/tv_grab_file: parse took 0 seconds
2022-11-10 10:58:45.726 xmltv: /usr/bin/tv_grab_file:  channels   tot=   13 new=    0 mod=    0
2022-11-10 10:58:45.726 xmltv: /usr/bin/tv_grab_file:  brands     tot=    0 new=    0 mod=    0
2022-11-10 10:58:45.726 xmltv: /usr/bin/tv_grab_file:  seasons    tot=    0 new=    0 mod=    0
2022-11-10 10:58:45.726 xmltv: /usr/bin/tv_grab_file:  episodes   tot=    0 new=    0 mod=    0
2022-11-10 10:58:45.726 xmltv: /usr/bin/tv_grab_file:  broadcasts tot=    0 new=    0 mod=    0

**Comment by epg2xml** [comment]
사이트가 리뉴얼 되었네요. 주말은 지나야 수정할 수 있을듯 합니다.

**Comment by epg2xml** [comment]
예전 사이트와 비슷해서 생각보다 금방 해결되었습니다. 확인해보세요.

**Comment by Taemni** [comment]
정상 작동합니다. 감사합니다.

**Comment by agwal** [comment]
저는 SK채널리스트 업데이트가 안되는것 같네요..

2022/11/12 18:00:17 INFO     PROV     123: [KT   ] 309 service channels loaded from cache.
2022/11/12 18:00:17 INFO     PROV     123: [LG   ] 350 service channels loaded from cache.
2022/11/12 18:00:17 INFO     PROV     123: [SK   ] 000 service channels loaded from cache.
2022/11/12 18:00:17 INFO     PROV     123: [DAUM ] 372 service channels loaded from cache.
2022/11/12 18:00:17 INFO     PROV     123: [NAVER] 476 service channels loaded from cache.
2022/11/12 18:00:17 INFO     PROV     123: [WAVVE] 162 service channels loaded from cache.
2022/11/12 18:00:17 INFO     PROV     123: [TVING] 457 service channels loaded from cache.
2022/11/12 18:00:17 INFO     PROV     123: [SPOTV] 007 service channels loaded from cache.

**Comment by epg2xml** [comment]
> 정상 작동합니다. 감사합니다. 앞으로 최대 2일치만 가져올 수 있는 건가요?

3일 주는 경우도 있네요. 날짜의 경계에서 2-3일이 되나봅니다. 수정이 필요하겠네요.
