### ISSUE TITLE
wavve 서비스 채널 요청 에러

### ISSUE THREAD

**Issue by Taemni** [epg2xml/epg2xml#31]
8월 1일 00시부터 발생한 것 같습니다.
확인 부탁드립니다!

```
2023-08-01 14:17:57.525 spawn: Executing "/usr/bin/tv_grab_file"
2023-08-01 14:18:14.616 spawn: 2023/08/01 14:18:14 INFO     PROV     118: [KT   ] 244 service channels successfully fetched from server.
2023-08-01 14:18:16.798 spawn: 2023/08/01 14:18:16 INFO     PROV     118: [LG   ] 353 service channels successfully fetched from server.
2023-08-01 14:18:17.983 spawn: 2023/08/01 14:18:17 INFO     PROV     118: [SK   ] 274 service channels successfully fetched from server.
2023-08-01 14:18:30.002 spawn: 2023/08/01 14:18:30 INFO     PROV     118: [DAUM ] 391 service channels successfully fetched from server.
2023-08-01 14:18:37.168 spawn: 2023/08/01 14:18:37 INFO     PROV     118: [NAVER] 473 service channels successfully fetched from server.
2023-08-01 14:18:37.192 spawn: 2023/08/01 14:18:37 ERROR    UTILS     38: 요청 중 에러: 403 Client Error: Forbidden for url: https://apis.wavve.com/live/epgs?enddatetime=2023-08-01+15%3A00&genre=all&limit=200&offset=0&startdatetime=2023-08-01+12%3A00&apikey=E5F3E0D30947AA5440556471321BB6D9&credential=none&device=pc&drm=wm&partner=pooq&pooqzone=none®ion=kor&targetage=auto
2023-08-01 14:18:38.195 spawn: 2023/08/01 14:18:38 ERROR    PROV     120: [WAVVE] Exception while retrieving service channels:
2023-08-01 14:18:38.195 spawn: Traceback (most recent call last):
2023-08-01 14:18:38.195 spawn:   File "/usr/local/lib/python3.8/dist-packages/epg2xml/providers/__init__.py", line 117, in load_svc_channels
2023-08-01 14:18:38.195 spawn:     self.get_svc_channels()
2023-08-01 14:18:38.195 spawn:   File "/usr/local/lib/python3.8/dist-packages/epg2xml/providers/wavve.py", line 55, in get_svc_channels
2023-08-01 14:18:38.195 spawn:     for x in self.request(self.url, params=self.params)["list"]
2023-08-01 14:18:38.195 spawn: TypeError: string indices must be integers
2023-08-01 14:18:38.384 xmltv: /usr/bin/tv_grab_file: grab took 41 seconds
2023-08-01 14:18:38.384 xmltv: /usr/bin/tv_grab_file: parse took 0 seconds
2023-08-01 14:18:38.384 xmltv: /usr/bin/tv_grab_file:  channels   tot=    0 new=    0 mod=    0
2023-08-01 14:18:38.384 xmltv: /usr/bin/tv_grab_file:  brands     tot=    0 new=    0 mod=    0
2023-08-01 14:18:38.384 xmltv: /usr/bin/tv_grab_file:  seasons    tot=    0 new=    0 mod=    0
2023-08-01 14:18:38.384 xmltv: /usr/bin/tv_grab_file:  episodes   tot=    0 new=    0 mod=    0
2023-08-01 14:18:38.384 xmltv: /usr/bin/tv_grab_file:  broadcasts tot=    0 new=    0 mod=    0
```

**Comment by epg2xml** [comment]
잘 되는 것을 확인했습니다. Client IP가 Ban일 가능성이 높으니 다른 IP에서 해보시길 바랍니다.
