### ISSUE TITLE
예외처리를 추가해주시면 좋을 듯 합니다.

### ISSUE THREAD

**Issue by projectdhs** [epg2xml/epg2xml#4]
웨이브 없어진 채널이 있어서 epg 추출이 이 채널 이후로 넘어가질 않았습니다.

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/epg2xml-main/epg2xml/__main__.py", line 131, in <module>
    main()
  File "/home/epg2xml-main/epg2xml/__main__.py", line 118, in main
    p.get_programs()
  File "/home/epg2xml-main/epg2xml/providers/wavve.py", line 61, in get_programs
    srcChannel = channeldict[_ch.svcid]
KeyError: 'K127'

**Comment by projectdhs** [comment]
추가로 모든 채널 업데이트 후 오류가 발생합니다.

python3 -m epg2xml update_channels

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/epg2xml-main/epg2xml/__main__.py", line 131, in <module>
    main()
  File "/home/epg2xml-main/epg2xml/__main__.py", line 124, in main
    load_channels(providers, conf)
  File "/home/epg2xml-main/epg2xml/providers/__init__.py", line 45, in load_channels
    'CHANNELS': p.svc_channel_list
TypeError: 'NoneType' object does not support item assignment

**Comment by epg2xml** [comment]
> 추가로 모든 채널 업데이트 후 오류가 발생합니다.
> 
> python3 -m epg2xml update_channels

위 문제는 해결했습니다. 

처음 제기하신 문제에 대해서는

K127 서비스 코드를 가지는 채널이 `Channel.json`에 있나요?
없어야 하지만 만약 있다면 `epg2xml.json`의 `WAVVE` > `MY_CHANNELS`를 수정해서 쓰시면 됩니다.
