### ISSUE TITLE
LG 채널 검색 중 Exception while retrieving service channels 이 발생합니다.

### ISSUE THREAD

**Issue by agwal** [epg2xml/epg2xml#44]
2023/10/22 00:56:44 INFO     PROV     118: [KT   ] 241 service channels successf                                                                                                                                                             ully fetched from server.
2023/10/22 00:56:45 ERROR    PROV     120: [LG   ] Exception while retrieving se                                                                                                                                                             rvice channels:
Traceback (most recent call last):
  File "/volume1/docker/FF/data/epg2xml/epg2xml/providers/__init__.py", line 117                                                                                                                                                             , in load_svc_channels
    self.get_svc_channels()
  File "/volume1/docker/FF/data/epg2xml/epg2xml/providers/lg.py", line 47, in ge                                                                                                                                                             t_svc_channels
    cate = {x["urcBrdCntrTvChnlGnreCd"]: x["urcBrdCntrTvChnlGnreNm"] for x in da                                                                                                                                                             ta["brdGnreDtoList"]}
TypeError: string indices must be integers
</tv>

위와 같은 오류로 생성이 안되고 있네요. 어떤 오류인지 몰라서 남겨봅니다.
확인 한번 부탁 드립니다.
감사합니다.

**Comment by Taemni** [comment]
L사 시스템 개편으로 2023년 10월 20일 (금) 오후 10시 ~ 23일 (월) 오전 11시까지 웹 서비스가 일시 중지되어 에러가 발생하는 것으로 보입니다.

**Comment by agwal** [comment]
아 공지가 있었네요. 확인을 못했습니다.
다음번에는 오류나면 일단 점검 공지부터 확인해 봐야겠네요.
감사합니다.
