### ISSUE TITLE
제공자 서비스 채널 업데이트 중 오류 발생 시 예외 처리가 필요할 것 같습니다.

### ISSUE THREAD

**Issue by Taemni** [epg2xml/epg2xml#45]
이전 #44 이슈와 같은 제공자의 서비스 점검으로 오류가 발생하면 서비스 채널을 업데이트하는 과정에서 바로 종료되는 문제가 있는 것 같습니다.
최근 L사의 서비스 점검이 잦아, S사, D사를 추가로 적용하였는데 로그를 확인해 보면 L사에서 오류 발생 후 다음 제공자의 채널과 EPG 데이터가 진행되지 않고 바로 종료되는 것으로 보입니다.

```
2023-10-22 13:55:32.625 xmltv: /usr/bin/tv_grab_file: grab /usr/bin/tv_grab_file
2023-10-22 13:55:32.628 spawn: Executing "/usr/bin/tv_grab_file"
2023-10-22 13:55:49.422 spawn: 2023/10/22 13:55:49 INFO     PROV     119: [KT   ] 241 service channels successfully fetched from server.
2023-10-22 13:55:50.712 spawn: 2023/10/22 13:55:50 ERROR    PROV     121: [LG   ] Exception while retrieving service channels:
2023-10-22 13:55:50.712 spawn: Traceback (most recent call last):
2023-10-22 13:55:50.712 spawn:   File "/usr/local/lib/python3.8/dist-packages/epg2xml/providers/__init__.py", line 118, in load_svc_channels
2023-10-22 13:55:50.712 spawn:     self.get_svc_channels()
2023-10-22 13:55:50.712 spawn:   File "/usr/local/lib/python3.8/dist-packages/epg2xml/providers/lg.py", line 48, in get_svc_channels
2023-10-22 13:55:50.712 spawn:     cate = {x["urcBrdCntrTvChnlGnreCd"]: x["urcBrdCntrTvChnlGnreNm"] for x in data["brdGnreDtoList"]}
2023-10-22 13:55:50.712 spawn: TypeError: string indices must be integers
2023-10-22 13:55:50.753 xmltv: /usr/bin/tv_grab_file: grab took 18 seconds
2023-10-22 13:55:50.753 xmltv: /usr/bin/tv_grab_file: parse took 0 seconds
2023-10-22 13:55:50.753 xmltv: /usr/bin/tv_grab_file:  channels   tot=    0 new=    0 mod=    0
2023-10-22 13:55:50.753 xmltv: /usr/bin/tv_grab_file:  brands     tot=    0 new=    0 mod=    0
2023-10-22 13:55:50.753 xmltv: /usr/bin/tv_grab_file:  seasons    tot=    0 new=    0 mod=    0
2023-10-22 13:55:50.753 xmltv: /usr/bin/tv_grab_file:  episodes   tot=    0 new=    0 mod=    0
2023-10-22 13:55:50.753 xmltv: /usr/bin/tv_grab_file:  broadcasts tot=    0 new=    0 mod=    0
```

**Comment by iykkim** [comment]
저 역시도 지난 달에 같은 문제([#34](https://github.com/epg2xml/epg2xml/issues/34))로 문의를 했었던 사용자로서 개발자 분께 같은 요청을 드리고 싶습니다.
사이트 작업 등으로 데이터를 가져오지 못하는 경우, 해당 사이트는 넘어가고 다른 사이트들을 계속 진행하도록 해서 종료되지 않고 EPG 생성은 되도록 해주시면 더욱 좋겠습니다.

**Comment by epg2xml** [comment]
LG가 최근 점검이 잦네요. 말씀하신대로 예외처리하도록 하겠습니다.
