### ISSUE TITLE
wavve 채널 오류

### ISSUE THREAD

**Issue by delifruit** [epg2xml/epg2xml#64]
안녕하세요..
wavve채널 epg를 불러올 때 아래처럼 에러가 발생합니다.
Channel.json을 지우고 해도 동일하네요
한 번 확인을 부탁드립니다~

2024-06-13 15:14:58.286 spawn: 2024/06/13 15:14:58 INFO     WAVVE    134: 001/020 KBS 2TV 
2024-06-13 15:14:58.286 spawn: Traceback (most recent call last):
2024-06-13 15:14:58.286 spawn:   File "/usr/bin/epg2xml", line 8, in 
2024-06-13 15:14:58.286 spawn:     sys.exit(main())
2024-06-13 15:14:58.286 spawn:              ^^^^^^
2024-06-13 15:14:58.286 spawn:   File "/usr/lib/python3.11/site-packages/epg2xml/__main__.py", line 52, in main
2024-06-13 15:14:58.286 spawn:     h.get_programs(conf.settings["parallel"])
2024-06-13 15:14:58.286 spawn:   File "/usr/lib/python3.11/site-packages/epg2xml/providers/__init__.py", line 433, in get_programs
2024-06-13 15:14:58.286 spawn:     p.get_programs()
2024-06-13 15:14:58.286 spawn:   File "/usr/lib/python3.11/site-packages/epg2xml/providers/wavve.py", line 135, in get_programs
2024-06-13 15:14:58.286 spawn:     for program in channeldict[_ch.svcid]["list"]:
2024-06-13 15:14:58.286 spawn:                    ~~~~~~~~~~~^^^^^^^^^^^
2024-06-13 15:14:58.286 spawn: KeyError: 'K02'

**Comment by epg2xml** [comment]
문제 없이 잘 됩니다. 웨이브만 그렇고 웨이브 다른 채널도 동일한 문제라면 IP 차단인지 확인해 보세요.

**Comment by delifruit** [comment]
네 확인 감사합니다~
지금은 잘 되네요..말씀하신대로 wavve에서 차단이 되었나봅니다.

**Comment by mykorea0330** [comment]
웨이브 epg가 총 3시간 분량의 정보만 수신되도록 변경이 된것 같습니다. 
1안) 3시간씩 하루 분량을 머지 해서 가공
2안) 3시간 분량씩 2시간 간격으로 cron 
저는 2안으로 사용중입니다

**Comment by epg2xml** [comment]
> 웨이브 epg가 총 3시간 분량의 정보만 수신되도록 변경이 된것 같습니다.
> 1안) 3시간씩 하루 분량을 머지 해서 가공
> 2안) 3시간 분량씩 2시간 간격으로 cron
> 저는 2안으로 사용중입니다

분석 감사합니다. 1안으로 수정했습니다.
