### ISSUE TITLE
SK 에러나는 것은 어떻게 고치나요?

### ISSUE THREAD

**Issue by category-9431** [epg2xml/epg2xml#67]
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/volume1/homes/bomjoo/epg2xml-main/epg2xml/__main__.py", line 70, in <module>
    main()
  File "/volume1/homes/bomjoo/epg2xml-main/epg2xml/__main__.py", line 52, in main
    h.get_programs(conf.settings["parallel"])
  File "/volume1/homes/bomjoo/epg2xml-main/epg2xml/providers/__init__.py", line 433, in get_programs
    p.get_programs()
  File "/volume1/homes/bomjoo/epg2xml-main/epg2xml/providers/wavve.py", line 133, in get_programs
    for ch in self.__get("/live/epgs", params=params)["list"]:
TypeError: string indices must be integers

**Comment by epg2xml** [comment]
로그에 따르면 wavve가 문제의 원인 같습니다. 얼마전부터 구버전의 urllib3로는 wavve에 403 Request Blocked 에러가 발생하는데 아래와 같이 urllib3를 업데이트 하시면 됩니다.

```sh
pip install -U urllib3
```

urllib3 2.2.3에서 정상 동작하는 것을 확인했습니다.

**Comment by youth1127** [comment]
혹시 참고하실 분 있어서 남겨봅니다.
![https://github.com/epg2xml/epg2xml/issues/68#issuecomment-2547261788]
