### ISSUE TITLE
67번 글과 같은 에러입니다.

### ISSUE THREAD

**Issue by youth1127** [epg2xml/epg2xml#68]
**항상 잘 쓰고 있어서 감사합니다**

sk채널의 문제는 아닌거 같고, epg2xml.json에서 네이버만 설정하여도 에러가 나옵니다.

...생략...
```
python -m epg2xml run
2024/12/02 12:55:59 INFO     PROV     294: [KT   ] 306 service channels loaded from cache
2024/12/02 12:55:59 INFO     PROV     294: [LG   ] 000 service channels loaded from cache
2024/12/02 12:55:59 INFO     PROV     294: [SK   ] 271 service channels loaded from cache
2024/12/02 12:55:59 INFO     PROV     294: [DAUM ] 391 service channels loaded from cache
2024/12/02 12:55:59 INFO     PROV     294: [NAVER] 465 service channels loaded from cache
2024/12/02 12:55:59 INFO     PROV     294: [WAVVE] 000 service channels loaded from cache
2024/12/02 12:55:59 INFO     PROV     294: [TVING] 325 service channels loaded from cache
2024/12/02 12:55:59 INFO     PROV     294: [SPOTV] 007 service channels loaded from cache
2024/12/02 12:55:59 INFO     PROV     344: [NAVER] 요청   8 - 불가   0 = 최종   8
2024/12/02 12:55:59 INFO     NAVER     70: 001/008 KBS2 <814582.naver>
2024/12/02 12:56:01 INFO     NAVER     70: 002/008 MBC <814588.naver>
2024/12/02 12:56:04 INFO     NAVER     70: 003/008 SBS <814592.naver>
2024/12/02 12:56:07 INFO     NAVER     70: 004/008 EBS1 <814595.naver>
2024/12/02 12:56:10 INFO     NAVER     70: 005/008 EBS2 <2438226.naver>
2024/12/02 12:56:13 INFO     NAVER     70: 006/008 경인 KBS1 <814597.naver>
2024/12/02 12:56:16 INFO     NAVER     70: 007/008 OBS 경인TV <814599.naver>
2024/12/02 12:56:19 INFO     NAVER     70: 008/008 tvN <814825.naver>
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/mnt/ssd1/nginx/epg2xml/epg2xml/__main__.py", line 70, in <module>
    main()
  File "/mnt/ssd1/nginx/epg2xml/epg2xml/__main__.py", line 52, in main
    h.get_programs(conf.settings["parallel"])
  File "/mnt/ssd1/nginx/epg2xml/epg2xml/providers/__init__.py", line 433, in get_programs
    p.get_programs()
  File "/mnt/ssd1/nginx/epg2xml/epg2xml/providers/wavve.py", line 131, in get_programs
    channeldict = {x["channelid"]: x for x in self.__get("/live/epgs", params=params)["list"]}
                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
TypeError: string indices must be integers, not 'str'
```

**Comment by epg2xml** [comment]
동일한 문제 같으니 해당 이슈의 댓글을 확인해주세요. https://github.com/epg2xml/epg2xml/issues/67#issuecomment-2510908352

**Comment by youth1127** [comment]
> 동일한 문제 같으니 해당 이슈의 댓글을 확인해주세요. [#67 (comment)](https://github.com/epg2xml/epg2xml/issues/67#issuecomment-2510908352)

덕분에 해결하였습니다
데비안12는 urllib3 버전이 1.26.12인데, 정책상 pip를 통한 모듈업데이트를 할 수가 없습니다.
그래서 python을 가상화로 돌려서 urllib3를 최신버전으로 업데이트 하니 잘 작동하네요.
