### ISSUE TITLE
WAVVE 동작 불가

### ISSUE THREAD

**Issue by leeys85** [epg2xml/epg2xml#69]
WAVVE 의 Channel 이 0개로 표시되고 아래와 같은 메시지를 출력합니다.

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/epg2xml/epg2xml/__main__.py", line 70, in <module>
    main()
  File "/opt/epg2xml/epg2xml/__main__.py", line 52, in main
    h.get_programs(conf.settings["parallel"])
  File "/opt/epg2xml/epg2xml/providers/__init__.py", line 433, in get_programs
    p.get_programs()
  File "/opt/epg2xml/epg2xml/providers/wavve.py", line 133, in get_programs
    for ch in self.__get("/live/epgs", params=params)["list"]:
TypeError: string indices must be integers

WAVVE 의 EPG 소스가 변경되어 발생하는 문제로 생각됩니다.

임시로 epg2xml/config.py 내부의 WAVVE 항목을 삭제하면 나머지 provider는 정상 동작 합니다.

**Comment by epg2xml** [comment]
너무 늦었지만 저는 그때도 잘 됐었고 지금도 잘 되고 있습니다. 모든 채널이 그러한지 특정채널만 그렇다면 안되는 채널은 어떤건지 알려주세요.
