### ISSUE TITLE
티빙 모듈에서 에러가 발생합니다

### ISSUE THREAD

**Issue by wowwoo** [epg2xml/epg2xml#7]
안녕하세요

티빙에 매핑한 채널의 EPG가 나오지 않아 확인해봤더니

2021/12/30 11:08:01 ERROR    MAIN     121: 'en'
Traceback (most recent call last):
  File "/home/wowwoo/EPG/epg2xml/__main__.py", line 119, in <module>
    main()
  File "/home/wowwoo/EPG/epg2xml/__main__.py", line 108, in main
    p.get_programs()
  File "/home/wowwoo/EPG/epg2xml/providers/tving.py", line 133, in get_programs
    _prog.title_sub = sch[get_from]["name"]["en"] if sch[get_from]["name"]["en"] else ""
KeyError: 'en'

위와 같은 에러가 발생하고 있습니다
3일치씩 EPG를 생성해서 언제부터 에러가 발생했는지는
모르겠습니다만 서비스 ID가 변경되었나 살펴봐도
변경된 것은 없는 것 같습니다

감사합니다

근데 다시 확인해보니 에러는 출력했는데
EPG는 생성이 됐습니다

문제가 아닌걸 올렸나봐요 ㅠㅜ

**Comment by epg2xml** [comment]
문제 수정했습니다. 알려 주셔서 고맙습니다.

**Comment by wowwoo** [comment]
> 문제 수정했습니다. 알려 주셔서 고맙습니다.

우와아앗 감사합니다!!
새해 복 많이 받으세요
